# frozen_string_literal: true

# The last of the ruby_llm removal. `chats`, `messages`, `tool_calls` and
# `models` were generated by that gem to persist LLM conversations; their
# models were four lines each of `acts_as_chat` / `acts_as_message` / etc.
#
# With the gem gone those macros are undefined, which production found before
# we did: development lazy-loads models, production eager-loads them, so
# `Chat` blew up at boot with NameError while every local check passed.
# Nothing in the app ever referenced these four classes.
#
# Dropped children-first so the foreign keys go before the tables they point
# at: tool_calls → messages → chats → models.
class DropRubyLlmTables < ActiveRecord::Migration[8.1]
  def up
    drop_table :tool_calls, if_exists: true
    drop_table :messages,   if_exists: true
    drop_table :chats,      if_exists: true
    drop_table :models,     if_exists: true
  end

  # Recreates the tables as the ruby_llm generators left them, so a rollback
  # lands on the schema this app actually had. The rows are gone for good,
  # and the models are not coming back — reinstating those means reinstalling
  # the gem and re-running its generators.
  def down
    create_table :models do |t|
      t.string   :model_id, null: false
      t.string   :name,     null: false
      t.string   :provider, null: false
      t.string   :family
      t.datetime :model_created_at
      t.integer  :context_window
      t.integer  :max_output_tokens
      t.date     :knowledge_cutoff
      t.json     :modalities,   default: {}
      t.json     :capabilities, default: []
      t.json     :pricing,      default: {}
      t.json     :metadata,     default: {}
      t.timestamps
    end
    add_index :models, [:provider, :model_id], unique: true
    add_index :models, :provider
    add_index :models, :family

    create_table :chats do |t|
      t.references :model, foreign_key: true
      t.timestamps
    end

    create_table :messages do |t|
      t.references :chat, null: false, foreign_key: true
      t.references :model, foreign_key: true
      t.string  :role, null: false
      t.text    :content
      t.json    :content_raw
      t.text    :thinking_text
      t.text    :thinking_signature
      t.integer :thinking_tokens
      t.integer :input_tokens
      t.integer :output_tokens
      t.integer :cached_tokens
      t.integer :cache_creation_tokens
      t.timestamps
    end
    add_index :messages, :role

    create_table :tool_calls do |t|
      t.references :message, null: false, foreign_key: true
      t.string :tool_call_id, null: false
      t.string :name,         null: false
      t.text   :thought_signature
      t.json   :arguments, default: {}
      t.timestamps
    end
    add_index :tool_calls, :tool_call_id, unique: true
    add_index :tool_calls, :name
  end
end
